### ISSUE TITLE
[help] getnetplugin: failed to get TRP

### ISSUE THREAD

**Issue by Elegant996** [redhat-nfvpe/kube-ansible#213]
Hi guys, I'm currently trying to create a multus-crd setup using the playbooks here as reference but am having issues adding a CRD network to the pod. I do have the appropriate clusterrole and clusterrolebindings for each node and get the appropriate output when checking my CRDs and networks:

```
[root@Kube-Master ~]# kubectl get crd
NAME                      AGE
networks.kubernetes.com   1d
[root@Kube-Master ~]# kubectl get networks
NAME           AGE
flannel-conf   36s
macvlan-conf   29s
```

However, when I try to create flannelpod/macvlanpod as seen on [doubtv's blog](http://dougbtv.com/nfvpe/2017/12/19/multus-crd/) the pod does not start and I receive the following error in `systemctl status kubelet`:

```
docker_sandbox.go:340] failed to read pod IP from plugin/docker: NetworkPlugin cni failed on the status hook for pod "flannelpod_default": CNI failed to retrieve network namespace path: cannot find network namespace for the terminated container "706d1f96593c67051e912aad8040c65db4b61b58c186777a6cd88f796924c56e"
cni.go:242] CNI failed to retrieve network namespace path: cannot find network namespace for the terminated container "706d1f96593c67051e912aad8040c65db4b61b58c186777a6cd88f796924c56e"
cni.go:277] Error deleting network: Multus: Err in getting k8s network from pod: getPodNetworkObj: failed in getting the netplugin: getnetplugin: failed to get TRP, refer Multus README.md for the usage guide: unknown
remote_runtime.go:115] StopPodSandbox "706d1f96593c67051e912aad8040c65db4b61b58c186777a6cd88f796924c56e" from runtime service failed: rpc error: code = Unknown desc = NetworkPlugin cni failed to teardown pod "flannelpod_default" network: Multus: Err in getting k8s network from pod: getPodNetworkObj: failed in getting the netplugin: getnetplugin: failed to get TRP, refer Multus README.md for the usage guide: unknown
kuberuntime_manager.go:800] Failed to stop sandbox {"docker" "706d1f96593c67051e912aad8040c65db4b61b58c186777a6cd88f796924c56e"}
```

The issue seems to be specific to the CRD, if I add flannel/macvlan as a default delegate to `multus-crd.yaml` and apply it, the pod will start with the delegated network but the CRDs are still ignored. Is there something I'm missing here? Thanks!

**Comment by dougbtv** [comment]
Alright, that's definitely permissions issues with Multus getting the CRDs from the Kube API. The error message in Multus is a bit dated -- TRPs (third party resources) were the precursor to CRDs (custom resource definitions)

Can you see if the clusterrolebindings were created properly? The playbooks should do those for you.

Mine, on a working install, look like:

```
[centos@kube-master ~]$ kubectl get clusterrolebinding | grep -i multus
multus-node-kube-master                                18d
multus-node-kube-node-1                                18d
[centos@kube-master ~]$ kubectl describe clusterrolebinding multus-node-kube-node-1
Name:         multus-node-kube-node-1
Labels:       <none>
Annotations:  <none>
Role:
  Kind:  ClusterRole
  Name:  multus-crd-overpowered
Subjects:
  Kind  Name                     Namespace
  ----  ----                     ---------
  User  system:node:kube-node-1  
[centos@kube-master ~]$ kubectl get clusterrole multus-crd-overpowered 
NAME                     AGE
multus-crd-overpowered   18d
```

**Comment by dougbtv** [comment]
I re-read and realize you said the clusterrole and clusterrolebindings are there... is it that the pods are created in another namespace? I honestly haven't tested outside the default namespace, and now I'm wondering if that may be something that's wrong with the permissions? Unsure, but, figured I'd add an extra comment.

**Comment by Elegant996** [comment]
Not sure what permissions I'd be missing:

```
[root@Kube-Master ~]# kubectl get clusterrolebinding | grep -i multus
multus-node-Kube-Master.example.com               17d
multus-node-Kube-Node01.example.com               17d
[root@Kube-Master ~]# kubectl describe clusterrolebinding multus-node-Kube-Node01.example.com
Name:         multus-node-Kube-Node01.example.com
Labels:       <none>
Annotations:  <none>
Role:
  Kind:  ClusterRole
  Name:  multus-crd-overpowered
Subjects:
  Kind  Name                                      Namespace
  ----  ----                                      ---------
  User  system:node:Kube-Node01.example.com
[root@Kube-Master ~]# kubectl get clusterrole multus-crd-overpowered
NAME                     AGE
multus-crd-overpowered   5d
```

**Comment by Elegant996** [comment]
Hit the wrong button, did not mean to close. Issue still persists. Thanks!

**Comment by dougbtv** [comment]
I'm currently on the road, but, when I return I'll pull up my notes and brew up an example of how to manually query the API from a node to help diagnose where the issue is! Thanks for re-opening, if you don't hear an update from me on the earlier side of next week, feel free to leave a comment to remind me to take a look.

**Comment by Elegant996** [comment]
Just a reminder to take a look at the permissions issue. Thanks!

**Comment by dougbtv** [comment]
I'm having some issues replicating the issue -- does it still happen on subsequent re-runs? I just spun up a cluster with the instructions from the [Multus + CRD blog article](http://dougbtv.com/nfvpe/2017/12/19/multus-crd/), but, I couldn't replicate the issue. 

Could you share your inventory and extra-vars file if you don't mind?

I'm also having a devil of a time trying to query the API from the node, I swear I've done it before, but, alas, I'm just not having luck today.

In some of the future development of Multus, I've added a bit to the line that outputs that error to make it easier to diagnose what's going on with Multus. Because it is notoriously tricky to figure out what the API is telling you when it fails to get the CRD in the current version @ master HEAD for Multus. In the future versions of kube-ansible, you'll have a way to change what version of Multus you're using (there's a pending PR for it, even). 

But for now, you could hack in a different version, if you change the file `./roles/multus-cni/tasks/main.yml` and change the play `name: Clone multus-cni` change:

```
    version: master
```

to 

```
    version: "dev/network-plumbing-working-group-crd-change"
```

This will give you some better error output, however, it also changes the namespace for the CRDs.

So you'd change an example pod to read like:

```
apiVersion: v1
kind: Pod
metadata:
  name: bothpod
  annotations:
    kubernetes-networks.cni.cncf.io: '[  
        { "name": "macvlan-conf" },
        { "name": "flannel-conf" }
    ]'
spec:
  containers:
  - name: bothpod
    command: ["/bin/bash", "-c", "sleep 2000000000000"]
    image: dougbtv/centos-network
    ports:
    - containerPort: 80
```
