### ISSUE TITLE
Virtual device plugin support -- to demonstrate device plugin

### ISSUE THREAD

**Issue by dougbtv** [redhat-nfvpe/kube-ansible#251]
For ONS summit 

- [x] build Kubernetes with [patch](https://github.com/kubernetes/kubernetes/compare/release-1.11...dashpole:device_id.patch)
- [x] Host binaries
- [x] Pull binaries in with playbooks
- [x] attach additional interfaces to nodes
- [x] determine number of nodes in cluster (master + n, 3? 4?)
- [x] attach extra virtio interfaces 
- [x] documentation for tutorial
- [x] build custom multus with device-id branch
- [x] include [ehost-device-cni](https://github.com/zshi-redhat/ehost-device-cni)
- [x] Set `FEATURE_GATES="ComputeDevice=true"`
- [x] automation to install [virt-network-device-plugin](https://github.com/zshi-redhat/virt-network-device-plugin#quick-start) itself.

**Comment by dougbtv** [comment]
Zenghui's repo @ https://github.com/zshi-redhat/virt-network-device-plugin

**Comment by dougbtv** [comment]
ehost-device-cni work dependent on: https://github.com/zshi-redhat/ehost-device-cni/issues/1

**Comment by rkamudhan** [comment]
@zshi-redhat @dougbtv how to generate the virtual virto interface in this setup ? what you mean by FEATURE_GATES="ComputeDevice=true" ?

**Comment by zenghui-shi** [comment]
> @zshi-redhat @dougbtv how to generate the virtual virto interface in this setup ? what you mean by FEATURE_GATES="ComputeDevice=true" ?

The general shell cmd used to attach virtio interface is : virsh attach-interface --domain vm_name --type bridge --model virtio --source bridge_name_on_host;   @dougbtv could tell how to automatically do it with ansible.

The feature_gates is to enable the ComputeDeivce feature which exposes DeviceID information in kubelet APIServer, the DeviceID information will then be queried by Multus;  it is based on old proposal of ComputeDevice since the new approaches of kubelet endpoint/checkpoint file are not developed when we start planning on this demo.

**Comment by rkamudhan** [comment]
So for the demo, we have to enable the FEATURE_GATES="ComputeDevice=true" ?

**Comment by dougbtv** [comment]
That feature gate is enabled when using these playbooks to setup the demo
lab

**Comment by dougbtv** [comment]
Also, the playbook does attach an interface, but, it's unreliable and I
never found a permanent solution hence the workaround in the README to
issue the command similar to what zshi recommended.

ETA:

```
virsh list --all | grep node | awk '{print $2}' | xargs -L1 -i virsh attach-interface --domain {} --type bridge --model virtio --source virbr0 --config --live
```

**Comment by rkamudhan** [comment]
@dougbtv Had a call with @zshi-redhat, it seems that we don't need the patch anymore, because multus recent commit take the checkpoint file and get the resource information. I think the Multus is pulled from the master in Kube-ansible, So I will try it. 

https://github.com/redhat-nfvpe/kube-ansible/tree/dev/ons-tutorial/contrib/multi-cluster#adding-additional-interfaces

Is having the script for the additional interfaces.

**Comment by dougbtv** [comment]
Yeah, feel free to remix it, however... I believe there's a step here somewhere to build Multus from a branch that was using DeviceID.
