### ISSUE TITLE
Load private SSH key onto host machine dynamically

### ISSUE THREAD

**Issue by dougbtv** [redhat-nfvpe/kube-ansible#61]
...needs a few missing things.

in my case one of which is location of the ssh key, but, there may be others.

**Comment by leifmadsen** [comment]
@dougbtv is this still the case? Can you document which template you're talking about? I'll go and dynamicize it :)

**Comment by dougbtv** [comment]
I think this was a quickly added issue when we were at astricon, but.... this is the one I'm speaking of specifically:

https://github.com/redhat-nfvpe/kube-centos-ansible/blob/master/inventory/examples/vms/vms.inventory#L19

That is the `ansible_ssh_private_key_file=` -- side note that like what I was talking about this morning was that we gen an SSH key on the virthost, then we never pull it down, it's left as a manual action, so... that's probably the bigger picture thing. At any rate, this is maybe something that's all gonna get ripped out. e.g. if we don't create the virtual machines in this playbook, maybe this gets moved into the extracted project.

**Comment by leifmadsen** [comment]
@dougbtv Thanks man. I think I'm just going to convert this issue to making it so our key is generated automatically for us, and then loaded from the local machine. I'll start working on this, because I think it'll make the documentation a lot easier to consume.

I probably need a flag or option that lets you override all this as well, since some people may be creating their own images, and they may very well have their own keys loaded into that image already.

**Comment by leifmadsen** [comment]
Also FYI, if you use `vm_ssh_key_path` in your `inventory/virthost/host_vars/virthost.yml` file, the template will already generate the dynamic SSH key path for you in `vms.local.generated`. I did this at AstriCon :)
