### ISSUE TITLE
vm.local.j2 has static elements

### ISSUE THREAD

**Issue by fepan** [redhat-nfvpe/kube-ansible#85]
The file vm.local.j2 has statically defined names for master and nodes sections:

```
[master]
kube-master

[nodes]
kube-node-1
kube-node-2
kube-node-3
```

This causes the generated inventory to be invalid when user specifies vm names other than default as defined in all.yml. The groups and host names in here should be generated from variable, it should also allow other groups, as not not all vms are k8s master or k8s nodes, there could be other helper VMs being created. 

I think we should split virtual_machines variable to multiple variables so we can easily use those names. One possible way:

```
master_prefix: kube-master
master_count: 1
minion_prefix: kube-node
minion_count: 3
other_vms:
  - my_custom_vm
  - my_other_vm
```

**Comment by leifmadsen** [comment]
I'd suggest we have a loop that works through a hash like I've done here:

https://github.com/leifmadsen/openstack-inventory-builder#create-a-job-template (see `instance_list`). That'll make it compatible with the `openstack-inventory-builder` and allow you to instantiate VMs that aren't being executed on by the playbooks.

The groups actually need to remain somewhat static, because you can't just pass in whatever groups you want for the playbooks to act appropriately, so you'll want to take the same approach as the `instance_list` method. Also, it'll make this continue to be compatible with `openstack-inventory-builder`.

```
- instance_list:
  - { name: kube-master, group: master, count: 1 }
  - { name: kube-minion, group: nodes, count: 3}
  - { name: something_else, group: whoknows, count: 2 }  # maybe external glusterFS nodes or something
```

**Comment by dougbtv** [comment]
Yeah, the way it has the like, hardcoded-list-o-names in `./group_vars/all.yml` isn't ideal at all. Happy to look at and test out any proposed solution, for sure.
